services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - tdrive_network

  tdrive_node:
    image: twakedrive/tdrive-node
    hostname: tdrive_node
    environment:
      - DEV=production
      - SEARCH_DRIVER=mongodb
      - DB_DRIVER=mongodb
      - PUBSUB_TYPE=local
    volumes:
      - ./docker-data/documents/:/storage/
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - tdrive_network

  frontend:
    image: twakedrive/tdrive-frontend
    restart: unless-stopped
    environment:
      - DEV=production
      - NODE_HOST=http://tdrive_node:4000
      - SSL_CERTS=off  # Dokploy se encargará del SSL y proxy
    expose:
      - "80"  # solo se expone internamente, sin tomar el puerto del host
    depends_on:
      - tdrive_node
    volumes:
      - ./docker-data/logs/nginx/:/var/log/nginx
      - ./docker-data/drive-preview/:/tdrive-core/web/medias/
      - ./docker-data/uploads/:/tdrive-core/web/upload/
    networks:
      - tdrive_network
networks:
  tdrive_network:
    driver: bridge

volumes:
  mongo-data:
